version: "3"

networks:
  work:

services:
  nginx:
    image: nginx:1.21.0-alpine
    container_name: nginx-work
    environment:
      TZ: Europe/Kiev
    ports:
      - "80:80" #Если ругается что какой-то порт занят попробуйте сменить первую 80 на что-то другое, допустим на - "83:80"
      - "443:443" #Если ругается что какой-то порт занят попробуйте сменить первую 443 на что-то другое, допустим на - "444:443"
    volumes:
      - ./src:/var/www/src
      - ./nginx/logs:/var/log/nginx #логи будут "синхронизироватся" в эту папку (nginx/logs)
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf #пробрасываем конфиг в нужную папку
    networks:
      - work

  php:
    image: php:8.1-fpm-alpine3.15
    container_name: php-work
    environment:
      TZ: Europe/Kiev
    volumes:
      - ./src:/var/www/src
    networks:
      - work
